#! /bin/bash
# For regex match, {,globs}

VSN=$1
[[ "$VSN" =~ ^[0-9][0-9][0-9]? ]] || {
    echo "Syntax: $0 <nn>

Create ./ensembl-branch-nn/ from cvs.sanger.ac.uk

REPLACING any existing directory of that name,

stripping the CVS/ directories afterwards,

then committing to Git.
" >&2
    exit 1
}

git diff --cached --quiet --exit-code && git diff --quiet --exit-code || {
    echo "$0 aborting: Working copy is not clean" >&2
    exit 2
}


[ -d ensembl-branch-$VSN ] || existed=creat
rm -rf ensembl-branch-$VSN

cvs -q -d :ext:cvs.sanger.ac.uk:/cvsroot/ensembl co \
    -r branch-ensembl-$VSN \
    -d ensembl-branch-$VSN \
    {ensembl,ensembl-external,ensembl-map,ensembl-compara,ensembl-variation,ensembl-functgenomics}/modules/Bio \
    {ensembl-webcode,ensembl-draw}/modules/Bio


find ensembl-branch-$VSN -type d -name CVS -print0 | xargs -r0 rm -rf

git add -A ensembl-branch-$VSN
git commit -m "ran $( basename $0 ) - ${existed:-updat}ed $VSN"
